# Generated by Django 6.0.8 on 2026-08-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Politics', 'Politics'), ('Sports', 'Sports'), ('Technology', 'Technology'), ('Business', 'Business'), ('Entertainment', 'Entertainment'), ('World', 'World'), ('Health', 'Health')], default='World', max_length=20),
        ),
    ]
